spring.application.name=viewerLimiterSystem

spring.datasource.url=jdbc:postgresql://localhost:5432/viewing_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.redis.host=localhost
spring.redis.port=6379
